use Examen_2OF
go
----PARTE 1
SELECT BOLETA.Fecha_Boleta, BOLETA.Estado_Boleta, DETALLE_BOLETA.Id_Producto, DETALLE_BOLETA.Cantidad, 
DETALLE_BOLETA.Precio_Venta FROM BOLETA JOIN DETALLE_BOLETA ON (BOLETA.Id_Boleta = DETALLE_BOLETA.Id_Boleta)
WHERE BOLETA.Fecha_Boleta BETWEEN '20070101' AND '20091231'

----PARTE 2
SELECT CLIENTE.Id_Cliente, CLIENTE.Correo,CLIENTE_NORMAL.Nombres ,CLIENTE_NORMAL.Apellido_PA, CLIENTE_NORMAL.Apellido_MA FROM CLIENTE JOIN CLIENTE_NORMAL ON (CLIENTE.Id_Cliente = CLIENTE_NORMAL.Id_Cliente)
ORDER BY CLIENTE_NORMAL.Apellido_PA, CLIENTE_NORMAL.Apellido_MA

----PARTE 3
SELECT EMPLEADO.Nombres, EMPLEADO.Apellido_PA
FROM EMPLEADO LEFT JOIN BOLETA ON (EMPLEADO.Id_Empleado = BOLETA.Id_Empleado) 
GROUP BY EMPLEADO.Apellido_PA, EMPLEADO.Nombres HAVING COUNT(BOLETA.Id_Empleado) = 0

----PARTE 4
SELECT PRODUCTO.Descripcion FROM PRODUCTO LEFT JOIN DETALLE_BOLETA ON (PRODUCTO.Id_Producto = DETALLE_BOLETA.Id_Producto)
WHERE PRODUCTO.Id_Producto NOT IN (SELECT DETALLE_BOLETA.Id_Producto FROM DETALLE_BOLETA)
GROUP BY PRODUCTO.Descripcion

---PARTE 5
SELECT BOLETA.Id_Boleta, BOLETA.Estado_Boleta, BOLETA.Fecha_Boleta, BOLETA.Id_Cliente, BOLETA.Id_Empleado, PRODUCTO.Descripcion FROM BOLETA JOIN DETALLE_BOLETA ON (BOLETA.Id_Boleta = DETALLE_BOLETA.Id_Boleta) 
JOIN PRODUCTO ON (PRODUCTO.Id_Producto = DETALLE_BOLETA.Id_Producto) 
WHERE BOLETA.Fecha_Boleta BETWEEN '20120101' AND '20120301' ORDER BY BOLETA.Id_Cliente ASC

----PARTE 6
SELECT EMPLEADO.Nombres, EMPLEADO.Apellido_PA FROM EMPLEADO JOIN BOLETA ON (EMPLEADO.Id_Empleado = BOLETA.Id_Empleado)
WHERE BOLETA.Fecha_Boleta NOT LIKE '%201204' AND BOLETA.Fecha_Boleta NOT LIKE '%201205'  AND BOLETA.Fecha_Boleta NOT LIKE '%201206' 

---PARTE 7

SELECT * FROM TIPO_PRODUCTO
SELECT * FROM DISTRITO
SELECT * FROM CLIENTE
SELECT * FROM CLIENTE_JURIDICO
SELECT * FROM CLIENTE_NORMAL
SELECT * FROM EMPLEADO
SELECT * FROM PRODUCTO
SELECT * FROM BOLETA
SELECT * FROM DETALLE_BOLETA
